[build]
  command = "npm run build"
  publish = "dist"
  functions = "backend-netlify/netlify/functions"

[dev]
  framework = "vite"
  functions = "backend-netlify/netlify/functions"
  command = "npm run dev"
  port = 8888
